export default {
  ROUTE_HOME: 'Home',
  ROUTE_CONTACT: 'Contact',
  ROUTE_HOME_TAB: 'HomeTab',
  ROUTE_CONTACT_TAB: 'ContactTab',
  ROUTE_AGENDA: 'ROUTE_AGENDA',
  ROUTE_PLACESTOVISIT: 'ROUTE_PLACESTOVISIT',
  GREETER: 'Welcome to \n',
  TCS: 'TCS',
  LOCATIONS: '- Chennai, Kochi',
  AGENDA: 'Agenda',
  PLACESTOVISIT: 'Places To Visit',
  CONTACTS: 'Contacts',
  CHENNAI:
    'Chennai Formerly Known as Madras, is the capital city of TamilNadu, the \n southernmost Indian State',
  PLACE: 'Mahabalipuram',
  SIGN_OUT: 'Sign Out',
  NAME: 'Name',
  PLACEHOLDER_NAME: 'User Name',
  PASSWORD: 'Password',
  SOMETHING_WENT_WRONG: 'Sorry! something went wrong',
};
